// <auto-generated />
using System;
using LigaCancer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LigaCancer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190423021238_RemoveFamilyFields")]
    partial class RemoveFamilyFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.ActivePatient", b =>
                {
                    b.Property<int>("ActivePatientId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Death");

                    b.Property<DateTime>("DeathDate");

                    b.Property<bool>("Discharge");

                    b.Property<DateTime>("DischargeDate");

                    b.Property<DateTime>("RegisterDate");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserUpdatedId");

                    b.HasKey("ActivePatientId");

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserUpdatedId");

                    b.ToTable("ActivePatients");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Complement");

                    b.Property<string>("HouseNumber");

                    b.Property<double>("MonthlyAmmountResidence");

                    b.Property<string>("Neighborhood");

                    b.Property<string>("ObservationAddress");

                    b.Property<int?>("PatientId");

                    b.Property<DateTime>("RegisterDate");

                    b.Property<int?>("ResidenceType");

                    b.Property<string>("Street");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserUpdatedId");

                    b.HasKey("AddressId");

                    b.HasIndex("PatientId");

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserUpdatedId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.CancerType", b =>
                {
                    b.Property<int>("CancerTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<DateTime>("RegisterDate");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserUpdatedId");

                    b.HasKey("CancerTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserUpdatedId");

                    b.ToTable("CancerTypes");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CRM");

                    b.Property<string>("Name");

                    b.Property<DateTime>("RegisterDate");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserUpdatedId");

                    b.HasKey("DoctorId");

                    b.HasIndex("CRM")
                        .IsUnique();

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserUpdatedId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.Family", b =>
                {
                    b.Property<int>("FamilyId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("MonthlyIncome");

                    b.Property<DateTime>("RegisterDate");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserUpdatedId");

                    b.HasKey("FamilyId");

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserUpdatedId");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.FamilyMember", b =>
                {
                    b.Property<int>("FamilyMemberId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Age");

                    b.Property<int?>("FamilyId");

                    b.Property<string>("Kinship");

                    b.Property<double?>("MonthlyIncome");

                    b.Property<string>("Name");

                    b.Property<DateTime>("RegisterDate");

                    b.Property<int>("Sex");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserUpdatedId");

                    b.HasKey("FamilyMemberId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserUpdatedId");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.FileAttachment", b =>
                {
                    b.Property<int>("FileAttachmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArchiveCategorie");

                    b.Property<string>("FileName");

                    b.Property<string>("FilePath");

                    b.Property<int?>("PatientId");

                    b.Property<DateTime>("RegisterDate");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserUpdatedId");

                    b.HasKey("FileAttachmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserUpdatedId");

                    b.ToTable("FileAttachments");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<DateTime>("RegisterDate");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserUpdatedId");

                    b.HasKey("MedicineId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserUpdatedId");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.Naturality", b =>
                {
                    b.Property<int>("NaturalityId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime>("RegisterDate");

                    b.Property<string>("State");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserUpdatedId");

                    b.HasKey("NaturalityId");

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserUpdatedId");

                    b.ToTable("Naturalities");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Age");

                    b.Property<string>("CPF");

                    b.Property<int>("CivilState");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<bool>("FamiliarityGroup");

                    b.Property<int?>("FamilyId");

                    b.Property<string>("FirstName");

                    b.Property<int?>("NaturalityId");

                    b.Property<int?>("PatientInformationId");

                    b.Property<string>("Profession");

                    b.Property<string>("RG");

                    b.Property<DateTime>("RegisterDate");

                    b.Property<int>("Sex");

                    b.Property<string>("Surname");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserUpdatedId");

                    b.HasKey("PatientId");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("FamilyId");

                    b.HasIndex("NaturalityId");

                    b.HasIndex("PatientInformationId");

                    b.HasIndex("RG")
                        .IsUnique();

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserUpdatedId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.PatientInformation", b =>
                {
                    b.Property<int>("PatientInformationId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ActivePatientId");

                    b.Property<DateTime>("RegisterDate");

                    b.Property<DateTime>("TreatmentbeginDate");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserUpdatedId");

                    b.HasKey("PatientInformationId");

                    b.HasIndex("ActivePatientId");

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserUpdatedId");

                    b.ToTable("PatientInformation");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.Phone", b =>
                {
                    b.Property<int>("PhoneId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Number");

                    b.Property<string>("ObservationNote");

                    b.Property<int?>("PatientId");

                    b.Property<int>("PhoneType");

                    b.Property<DateTime>("RegisterDate");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserUpdatedId");

                    b.HasKey("PhoneId");

                    b.HasIndex("PatientId");

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserUpdatedId");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.Presence", b =>
                {
                    b.Property<int>("PresenceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("PatientId");

                    b.Property<DateTime>("PresenceDateTime");

                    b.Property<DateTime>("RegisterDate");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserUpdatedId");

                    b.HasKey("PresenceId");

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserUpdatedId");

                    b.ToTable("Presences");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.TreatmentPlace", b =>
                {
                    b.Property<int>("TreatmentPlaceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<DateTime>("RegisterDate");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserUpdatedId");

                    b.HasKey("TreatmentPlaceId");

                    b.HasIndex("City")
                        .IsUnique();

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserUpdatedId");

                    b.ToTable("TreatmentPlaces");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.RelationModels.PatientInformationCancerType", b =>
                {
                    b.Property<int>("PatientInformationId");

                    b.Property<int>("CancerTypeId");

                    b.HasKey("PatientInformationId", "CancerTypeId");

                    b.HasIndex("CancerTypeId");

                    b.ToTable("PatientInformationCancerType");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.RelationModels.PatientInformationDoctor", b =>
                {
                    b.Property<int>("PatientInformationId");

                    b.Property<int>("DoctorId");

                    b.HasKey("PatientInformationId", "DoctorId");

                    b.HasIndex("DoctorId");

                    b.ToTable("PatientInformationDoctor");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.RelationModels.PatientInformationMedicine", b =>
                {
                    b.Property<int>("PatientInformationId");

                    b.Property<int>("MedicineId");

                    b.HasKey("PatientInformationId", "MedicineId");

                    b.HasIndex("MedicineId");

                    b.ToTable("PatientInformationMedicine");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.RelationModels.PatientInformationTreatmentPlace", b =>
                {
                    b.Property<int>("PatientInformationId");

                    b.Property<int>("TreatmentPlaceId");

                    b.HasKey("PatientInformationId", "TreatmentPlaceId");

                    b.HasIndex("TreatmentPlaceId");

                    b.ToTable("PatientInformationTreatmentPlace");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("DeletedDate");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("RegisterDate");

                    b.ToTable("ApplicationUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.ActivePatient", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserCreatedId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserUpdated")
                        .WithMany()
                        .HasForeignKey("UserUpdatedId");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.Address", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.PatientModels.Patient")
                        .WithMany("Addresses")
                        .HasForeignKey("PatientId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserCreatedId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserUpdated")
                        .WithMany()
                        .HasForeignKey("UserUpdatedId");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.CancerType", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserCreatedId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserUpdated")
                        .WithMany()
                        .HasForeignKey("UserUpdatedId");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.Doctor", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserCreatedId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserUpdated")
                        .WithMany()
                        .HasForeignKey("UserUpdatedId");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.Family", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserCreatedId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserUpdated")
                        .WithMany()
                        .HasForeignKey("UserUpdatedId");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.FamilyMember", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.PatientModels.Family")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("FamilyId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserCreatedId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserUpdated")
                        .WithMany()
                        .HasForeignKey("UserUpdatedId");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.FileAttachment", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.PatientModels.Patient")
                        .WithMany("FileAttachments")
                        .HasForeignKey("PatientId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserCreatedId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserUpdated")
                        .WithMany()
                        .HasForeignKey("UserUpdatedId");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.Medicine", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserCreatedId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserUpdated")
                        .WithMany()
                        .HasForeignKey("UserUpdatedId");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.Naturality", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserCreatedId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserUpdated")
                        .WithMany()
                        .HasForeignKey("UserUpdatedId");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.Patient", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.PatientModels.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId");

                    b.HasOne("LigaCancer.Data.Models.PatientModels.Naturality", "Naturality")
                        .WithMany()
                        .HasForeignKey("NaturalityId");

                    b.HasOne("LigaCancer.Data.Models.PatientModels.PatientInformation", "PatientInformation")
                        .WithMany()
                        .HasForeignKey("PatientInformationId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserCreatedId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserUpdated")
                        .WithMany()
                        .HasForeignKey("UserUpdatedId");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.PatientInformation", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.PatientModels.ActivePatient", "ActivePatient")
                        .WithMany()
                        .HasForeignKey("ActivePatientId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserCreatedId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserUpdated")
                        .WithMany()
                        .HasForeignKey("UserUpdatedId");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.Phone", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.PatientModels.Patient")
                        .WithMany("Phones")
                        .HasForeignKey("PatientId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserCreatedId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserUpdated")
                        .WithMany()
                        .HasForeignKey("UserUpdatedId");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.Presence", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserCreatedId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserUpdated")
                        .WithMany()
                        .HasForeignKey("UserUpdatedId");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.PatientModels.TreatmentPlace", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserCreatedId");

                    b.HasOne("LigaCancer.Data.Models.ApplicationUser", "UserUpdated")
                        .WithMany()
                        .HasForeignKey("UserUpdatedId");
                });

            modelBuilder.Entity("LigaCancer.Data.Models.RelationModels.PatientInformationCancerType", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.PatientModels.CancerType", "CancerType")
                        .WithMany("PatientInformationCancerTypes")
                        .HasForeignKey("CancerTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LigaCancer.Data.Models.PatientModels.PatientInformation", "PatientInformation")
                        .WithMany("PatientInformationCancerTypes")
                        .HasForeignKey("PatientInformationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LigaCancer.Data.Models.RelationModels.PatientInformationDoctor", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.PatientModels.Doctor", "Doctor")
                        .WithMany("PatientInformationDoctors")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LigaCancer.Data.Models.PatientModels.PatientInformation", "PatientInformation")
                        .WithMany("PatientInformationDoctors")
                        .HasForeignKey("PatientInformationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LigaCancer.Data.Models.RelationModels.PatientInformationMedicine", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.PatientModels.Medicine", "Medicine")
                        .WithMany("PatientInformationMedicines")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LigaCancer.Data.Models.PatientModels.PatientInformation", "PatientInformation")
                        .WithMany("PatientInformationMedicines")
                        .HasForeignKey("PatientInformationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LigaCancer.Data.Models.RelationModels.PatientInformationTreatmentPlace", b =>
                {
                    b.HasOne("LigaCancer.Data.Models.PatientModels.PatientInformation", "PatientInformation")
                        .WithMany("PatientInformationTreatmentPlaces")
                        .HasForeignKey("PatientInformationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LigaCancer.Data.Models.PatientModels.TreatmentPlace", "TreatmentPlace")
                        .WithMany("PatientInformationTreatmentPlaces")
                        .HasForeignKey("TreatmentPlaceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
