// <auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RVCC.Data.Migrations
{
    public partial class Attendant : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM VisitorAttendanceTypes");
            migrationBuilder.Sql("DELETE FROM AuditVisitorAttendanceTypes");

            migrationBuilder.AddColumn<int>(
                name: "AttendantId",
                table: "VisitorAttendanceTypes",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "AttendantId",
                table: "AuditVisitorAttendanceTypes",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateTable(
                name: "Attendants",
                columns: table => new
                {
                    AttendantId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CPF = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Phone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Note = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RegisterTime = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedTime = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Attendants", x => x.AttendantId);
                });

            migrationBuilder.CreateTable(
                name: "AuditAttendants",
                columns: table => new
                {
                    AuditAttendantId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    AttendantId = table.Column<int>(type: "int", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CPF = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Phone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Note = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AuditDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UserName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AuditAction = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AuditAttendants", x => x.AuditAttendantId);
                });

            migrationBuilder.CreateIndex(
                name: "IX_VisitorAttendanceTypes_AttendantId",
                table: "VisitorAttendanceTypes",
                column: "AttendantId");

            migrationBuilder.AddForeignKey(
                name: "FK_VisitorAttendanceTypes_Attendants_AttendantId",
                table: "VisitorAttendanceTypes",
                column: "AttendantId",
                principalTable: "Attendants",
                principalColumn: "AttendantId",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_VisitorAttendanceTypes_Attendants_AttendantId",
                table: "VisitorAttendanceTypes");

            migrationBuilder.DropTable(
                name: "Attendants");

            migrationBuilder.DropTable(
                name: "AuditAttendants");

            migrationBuilder.DropIndex(
                name: "IX_VisitorAttendanceTypes_AttendantId",
                table: "VisitorAttendanceTypes");

            migrationBuilder.DropColumn(
                name: "AttendantId",
                table: "VisitorAttendanceTypes");

            migrationBuilder.DropColumn(
                name: "AttendantId",
                table: "AuditVisitorAttendanceTypes");
        }
    }
}
