// <auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RVCC.Data.Migrations
{
    public partial class AuxiliarAccessoryType : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "AuditAuxiliarAccessoryTypes",
                columns: table => new
                {
                    AuditAuxiliarAccessoryTypeId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    AuxiliarAccessoryTypeId = table.Column<int>(type: "int", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AuditDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UserName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AuditAction = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AuditAuxiliarAccessoryTypes", x => x.AuditAuxiliarAccessoryTypeId);
                });

            migrationBuilder.CreateTable(
                name: "AuditPatientAuxiliarAccessoryTypes",
                columns: table => new
                {
                    AuditAuxiliarAccessoryTypeId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    PatientAuxiliarAccessoryTypeId = table.Column<int>(type: "int", nullable: false),
                    PatientId = table.Column<int>(type: "int", nullable: false),
                    AuxiliarAccessoryTypeId = table.Column<int>(type: "int", nullable: false),
                    AuxiliarAccessoryTypeTime = table.Column<int>(type: "int", nullable: false),
                    DuoDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Note = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AuditDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UserName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AuditAction = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AuditPatientAuxiliarAccessoryTypes", x => x.AuditAuxiliarAccessoryTypeId);
                });

            migrationBuilder.CreateTable(
                name: "AuxiliarAccessoryTypes",
                columns: table => new
                {
                    AuxiliarAccessoryTypeId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RegisterTime = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedTime = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AuxiliarAccessoryTypes", x => x.AuxiliarAccessoryTypeId);
                });

            migrationBuilder.CreateTable(
                name: "PatientAuxiliarAccessoryTypes",
                columns: table => new
                {
                    PatientAuxiliarAccessoryTypeId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    AuxiliarAccessoryTypeTime = table.Column<int>(type: "int", nullable: false),
                    DuoDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Note = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PatientId = table.Column<int>(type: "int", nullable: false),
                    AuxiliarAccessoryTypeId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PatientAuxiliarAccessoryTypes", x => x.PatientAuxiliarAccessoryTypeId);
                    table.ForeignKey(
                        name: "FK_PatientAuxiliarAccessoryTypes_AuxiliarAccessoryTypes_AuxiliarAccessoryTypeId",
                        column: x => x.AuxiliarAccessoryTypeId,
                        principalTable: "AuxiliarAccessoryTypes",
                        principalColumn: "AuxiliarAccessoryTypeId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_PatientAuxiliarAccessoryTypes_Patients_PatientId",
                        column: x => x.PatientId,
                        principalTable: "Patients",
                        principalColumn: "PatientId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_PatientAuxiliarAccessoryTypes_AuxiliarAccessoryTypeId",
                table: "PatientAuxiliarAccessoryTypes",
                column: "AuxiliarAccessoryTypeId");

            migrationBuilder.CreateIndex(
                name: "IX_PatientAuxiliarAccessoryTypes_PatientId",
                table: "PatientAuxiliarAccessoryTypes",
                column: "PatientId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AuditAuxiliarAccessoryTypes");

            migrationBuilder.DropTable(
                name: "AuditPatientAuxiliarAccessoryTypes");

            migrationBuilder.DropTable(
                name: "PatientAuxiliarAccessoryTypes");

            migrationBuilder.DropTable(
                name: "AuxiliarAccessoryTypes");
        }
    }
}
